project:
  type: book
  output-dir: docs

book:
  title: "Mortalidad en Medellín"
  sidebar:
    logo: logo.png
    collapse-level: 1
  chapters:
    - index.qmd
    - eda_VIS_Entregable2.ipynb

format:
  html:
    theme: flatly
    toc: true
    toc-title: "Contenido"
    toc-location: right
    toc-depth: 4
    toc-expand: true
    number-sections: false